### ISSUE TITLE
Code for Figure 8 in the paper

### ISSUE THREAD

**Issue by yaseryacoob** [eclipse-t2i/lambda-eclipse-inference#1]
Can you please share the code for Figure 8 in your paper about interpolation?
thanks

**Comment by Maitreyapatel** [comment]
Hello @yaseryacoob,
Thanks for checking in. We will release the code/notebook within the next few days.

Meanwhile, it's very easy to implement, please refer to the below instructions:
1. Fix the seed for the prior and unet model.
2. Given all four combinations of subjects extract and save prior model output. 
3. You can perform linear or spherical interpolations between these four embeddings from prior models.
4. Use UNet model to generate images corresponding to each interpolations.

**Comment by Maitreyapatel** [comment]
Hello @yaseryacoob,

Thanks for waiting! Please find the corresponding interpolation script: [interpolation.py](https://github.com/eclipse-t2i/lambda-eclipse-inference/blob/main/interpolation.py)

Best!
